const lang = {
    en: {
        A_COLLECTION_OF: `A collection of`,
        BY: `by`,
        BY_THIS_AUTHOR: `by this author`,
        GOTO_FRONT_PAGE: `Go to the front page`,
        LATEST_POSTS: `Latest Posts`,
        IS_REQUIRED: `is required`,
        MIN_READ: `min read`,
        MORE_IN: `More in`,
        MORE_POSTS: `More posts`,
        MORE_POSTS_SM: `more posts`,
        NEXT: `Next`,
        NO_POSTS: `No posts`,
        PAGE_NOT_FOUND: `Page not found`,
        POST: `post`,
        POSTS: `posts`,
        PREVIOUS: `Previous`,
        READ: `Read`,
        SEE_ALL: `See all`,
        SUBSCRIBED_TO: `You've successfully subscribed to`,
        WEBSITE: `Website`,
        MULTIPLE_AUTHORS: `Multiple authors`,
    },
    pl: {
        A_COLLECTION_OF: `Kolekcja z`,
        BY: `przez`,
        BY_THIS_AUTHOR: `tego autora`,
        GOTO_FRONT_PAGE: `Przejdź do strony głównej`,
        LATEST_POSTS: `Ostatnie Wpisy`,
        IS_REQUIRED: `Wymagane`,
        MIN_READ: `min czytania`,
        MORE_IN: `Więcej na`,
        MORE_POSTS: `Więcej wpisów`,
        MORE_POSTS_SM: `więcej wpisów`,
        NEXT: `Następny`,
        NO_POSTS: `Brak wpisów`,
        PAGE_NOT_FOUND: `Strona nie istnieje`,
        POST: `wpis`,
        POSTS: `wpisy`,
        PREVIOUS: `Wcześniejszsy`,
        READ: `Czytaj`,
        SEE_ALL: `Zobacz wszystkie`,
        SUBSCRIBED_TO: `Pomyślnie zasubskrybowano`,
        WEBSITE: `Strona`,
        MULTIPLE_AUTHORS: `Wielu autorów`,
    },
}

module.exports = lang
